"""Generate database/weather_seed.sql from the enriched extraction CSV.

Reads the four final fields (date, weather_system, pressure_level, subdivisions),
splits the multi-valued pressure/subdivision lists, and emits INSERT statements with
explicit primary keys so the junction rows resolve deterministically.

Usage:
    python database/load_csv_to_sql.py [path/to/input.csv]

Then load the result into MySQL:
    mysql < database/weather_data.sql      # schema
    mysql weather_data_system < database/weather_seed.sql   # data
"""
from pathlib import Path
import csv
import sys

REPO = Path(__file__).resolve().parent.parent
DEFAULT_CSV = REPO / "output_aiws_corrected_subdivisions_fixed.csv"
OUT_PATH = REPO / "database" / "weather_seed.sql"

VALID_SYSTEMS = {"WD", "CYCIR", "Trough"}


def sql_str(value: str) -> str:
    """Quote/escape a string literal for MySQL."""
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def split_list(value: str) -> list[str]:
    return [part.strip() for part in (value or "").split(";") if part.strip()]


def hpa_of(label: str) -> int:
    """'700 hPa' -> 700."""
    return int(label.split()[0])


def chunked(rows: list[str], size: int = 200):
    for i in range(0, len(rows), size):
        yield rows[i : i + size]


def build_sql(csv_path: Path) -> str:
    with csv_path.open(newline="", encoding="utf-8") as fh:
        rows = [r for r in csv.DictReader(fh) if (r.get("weather_system") or "").strip() in VALID_SYSTEMS]

    # --- assign deterministic ids to dimension values ---
    dates = sorted({r["date"] for r in rows})
    date_id = {d: i + 1 for i, d in enumerate(dates)}

    subs = sorted({s for r in rows for s in split_list(r["subdivisions"])})
    sub_id = {s: i + 1 for i, s in enumerate(subs)}

    labels = sorted({p for r in rows for p in split_list(r["pressure_level"])}, key=hpa_of)
    label_id = {p: i + 1 for i, p in enumerate(labels)}

    # --- weather_systems rows (one per CSV row) with per-date sequence ---
    system_rows: list[tuple[int, int, int, str]] = []  # (sys_id, entry_id, seq, type)
    sys_sub_rows: list[tuple[int, int]] = []
    sys_pl_rows: list[tuple[int, int]] = []
    seq_by_date: dict[str, int] = {}

    for i, r in enumerate(rows, start=1):
        d = r["date"]
        seq_by_date[d] = seq_by_date.get(d, 0) + 1
        system_rows.append((i, date_id[d], seq_by_date[d], r["weather_system"]))
        for s in split_list(r["subdivisions"]):
            sys_sub_rows.append((i, sub_id[s]))
        for p in split_list(r["pressure_level"]):
            sys_pl_rows.append((i, label_id[p]))

    # --- emit ---
    out: list[str] = []
    out.append("-- Auto-generated by database/load_csv_to_sql.py. Do not edit by hand.")
    out.append(f"-- Source: {csv_path.name} ({len(rows)} systems, {len(dates)} dates)")
    out.append("USE weather_data_system;")
    out.append("")
    out.append("SET FOREIGN_KEY_CHECKS = 0;")
    for table in (
        "system_pressure_levels",
        "system_subdivisions",
        "weather_systems",
        "weather_entries",
        "pressure_levels",
        "subdivisions",
    ):
        out.append(f"TRUNCATE TABLE {table};")
    out.append("SET FOREIGN_KEY_CHECKS = 1;")
    out.append("")

    def emit(header: str, columns: str, table: str, values: list[str]) -> None:
        out.append(f"-- {header}")
        for batch in chunked(values):
            out.append(f"INSERT INTO {table} ({columns}) VALUES")
            out.append(",\n".join(batch) + ";")
        out.append("")

    emit(
        "Lookup: subdivisions",
        "id, name",
        "subdivisions",
        [f"({sub_id[s]}, {sql_str(s)})" for s in subs],
    )
    emit(
        "Lookup: pressure levels",
        "id, label, hpa",
        "pressure_levels",
        [f"({label_id[p]}, {sql_str(p)}, {hpa_of(p)})" for p in labels],
    )
    emit(
        "Bulletin dates",
        "id, entry_date",
        "weather_entries",
        [f"({date_id[d]}, {sql_str(d)})" for d in dates],
    )
    emit(
        "Weather systems",
        "id, entry_id, system_seq, weather_system",
        "weather_systems",
        [f"({sid}, {eid}, {seq}, {sql_str(t)})" for sid, eid, seq, t in system_rows],
    )
    emit(
        "Junction: system <-> subdivision",
        "system_id, subdivision_id",
        "system_subdivisions",
        [f"({sid}, {did})" for sid, did in sys_sub_rows],
    )
    emit(
        "Junction: system <-> pressure level",
        "system_id, pressure_level_id",
        "system_pressure_levels",
        [f"({sid}, {pid})" for sid, pid in sys_pl_rows],
    )

    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    csv_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV
    if not csv_path.exists():
        raise SystemExit(f"CSV not found: {csv_path}")
    OUT_PATH.write_text(build_sql(csv_path), encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(REPO)}")


if __name__ == "__main__":
    main()